
version: 2

sources:
    - name: circle
      schema: raw_data_circle
      tables:
          - name: parcel
            identifier: raw_cc_parcel
            description: "includes raw parcel data"
            columns:
              - name: Parcel_id
                description: "id of the parcel"
                tests:
                  - unique
                  - not_null
          - name: parcel_product
            identifier: raw_cc_parcel_product
            description: "shows products in a parcel"
            columns:
              - name: ParCEL_id
                description: "id of the parcel"
                tests:
                  - unique
                  - not_null
            
